#ifndef SIGNAL_ALGORITHM_STATUS_H
#define SIGNAL_ALGORITHM_STATUS_H

/**
 * @file signal_algorithm_status.h
 * @brief 独立纯算法层统一返回码；不依赖主工程或芯片寄存器。
 */

typedef enum
{
    SIGNAL_ALGORITHM_OK = 0,
    SIGNAL_ALGORITHM_INVALID_ARGUMENT,
    SIGNAL_ALGORITHM_INSUFFICIENT_DATA,
    SIGNAL_ALGORITHM_OUT_OF_RANGE,
    SIGNAL_ALGORITHM_BUFFER_TOO_SMALL,
    SIGNAL_ALGORITHM_NO_FEATURE,
    SIGNAL_ALGORITHM_NUMERIC_ERROR,
    SIGNAL_ALGORITHM_NOT_SUPPORTED
} signal_algorithm_status_t;

#endif /* SIGNAL_ALGORITHM_STATUS_H */
