#ifndef SIGNAL_MATH_BACKEND_CONFIG_H
#define SIGNAL_MATH_BACKEND_CONFIG_H

#define SIGNAL_MATH_BACKEND_REFERENCE_FLOAT 0
#define SIGNAL_MATH_BACKEND_IQMATH_RTS      1
#define SIGNAL_MATH_BACKEND_IQMATH_MATHACL  2

/* 默认保持标准 math.h，现有工程不会自动新增 IQMath 链接依赖。 */
#ifndef SIGNAL_MATH_BACKEND
#define SIGNAL_MATH_BACKEND SIGNAL_MATH_BACKEND_REFERENCE_FLOAT
#endif

#if ((SIGNAL_MATH_BACKEND != SIGNAL_MATH_BACKEND_REFERENCE_FLOAT) && \
     (SIGNAL_MATH_BACKEND != SIGNAL_MATH_BACKEND_IQMATH_RTS) && \
     (SIGNAL_MATH_BACKEND != SIGNAL_MATH_BACKEND_IQMATH_MATHACL))
#error "Unsupported SIGNAL_MATH_BACKEND value"
#endif

#endif /* SIGNAL_MATH_BACKEND_CONFIG_H */
