#ifndef SIGNAL_SSD1306_MSPM0G3507_H
#define SIGNAL_SSD1306_MSPM0G3507_H

#include <stdbool.h>
#include <stdint.h>

#include "ssd1306.h"
#include "ssd1306_mspm0_i2c.h"

/* This binding uses the I2C_INST symbol generated by SysConfig. */
ssd1306_status_t SignalSSD1306_MSPM0_Init(ssd1306_t *device,
    ssd1306_mspm0_i2c_t *bus, uint8_t address_7bit, bool rotate_180);

#endif /* SIGNAL_SSD1306_MSPM0G3507_H */
