#ifndef SIGNAL_HW_CONFIG_H
#define SIGNAL_HW_CONFIG_H

/**
 * @file signal_hw_config.h
 * @brief Competition-day peripheral selection and centralized parameters.
 *
 * This file selects intent.  The matching profile.syscfg remains the hardware
 * source of truth for pins, instances, DMA channels and Event routes.
 */

#define SIGNAL_HW_PROFILE_ADC_CAPTURE 1U
#define SIGNAL_HW_PROFILE_DUAL_ADC 2U
#define SIGNAL_HW_PROFILE_DAC_GENERATOR 3U
#define SIGNAL_HW_PROFILE_ADC_DAC 4U
#define SIGNAL_HW_PROFILE_FREQUENCY 5U
#define SIGNAL_HW_PROFILE_FULL_SIGNAL 6U

#ifndef SIGNAL_HW_PROFILE
#define SIGNAL_HW_PROFILE SIGNAL_HW_PROFILE_ADC_CAPTURE
#endif

#define SIGNAL_HW_SAMPLE_COUNT 1024U
#define SIGNAL_HW_ADC_SAMPLE_RATE_HZ 100000U
#define SIGNAL_HW_DAC_UPDATE_RATE_HZ 100000U
#define SIGNAL_HW_ADC_BITS 12U
#define SIGNAL_HW_ADC_REFERENCE_VOLTAGE_V 3.3f
#define SIGNAL_HW_UART_BAUD_RATE 115200U

#if (SIGNAL_HW_SAMPLE_COUNT == 0U) || (SIGNAL_HW_SAMPLE_COUNT > 65535U)
#error "SIGNAL_HW_SAMPLE_COUNT must fit the current ADC_DMA uint16_t count API"
#endif

#if (SIGNAL_HW_ADC_SAMPLE_RATE_HZ == 0U)
#error "SIGNAL_HW_ADC_SAMPLE_RATE_HZ must be nonzero"
#endif

#if (SIGNAL_HW_PROFILE == SIGNAL_HW_PROFILE_ADC_CAPTURE)
#define SIGNAL_HW_ENABLE_ADC_A 1
#define SIGNAL_HW_ENABLE_ADC_B 0
#define SIGNAL_HW_ENABLE_DAC 0
#define SIGNAL_HW_ENABLE_CAPTURE 0
#define SIGNAL_HW_ENABLE_COMPARATOR 0
#define SIGNAL_HW_ENABLE_UART_DEBUG 1
#elif (SIGNAL_HW_PROFILE == SIGNAL_HW_PROFILE_DUAL_ADC)
#define SIGNAL_HW_ENABLE_ADC_A 1
#define SIGNAL_HW_ENABLE_ADC_B 1
#define SIGNAL_HW_ENABLE_DAC 0
#define SIGNAL_HW_ENABLE_CAPTURE 0
#define SIGNAL_HW_ENABLE_COMPARATOR 0
#define SIGNAL_HW_ENABLE_UART_DEBUG 1
#elif (SIGNAL_HW_PROFILE == SIGNAL_HW_PROFILE_DAC_GENERATOR)
#define SIGNAL_HW_ENABLE_ADC_A 0
#define SIGNAL_HW_ENABLE_ADC_B 0
#define SIGNAL_HW_ENABLE_DAC 1
#define SIGNAL_HW_ENABLE_CAPTURE 0
#define SIGNAL_HW_ENABLE_COMPARATOR 0
#define SIGNAL_HW_ENABLE_UART_DEBUG 1
#elif (SIGNAL_HW_PROFILE == SIGNAL_HW_PROFILE_ADC_DAC)
#define SIGNAL_HW_ENABLE_ADC_A 1
#define SIGNAL_HW_ENABLE_ADC_B 0
#define SIGNAL_HW_ENABLE_DAC 1
#define SIGNAL_HW_ENABLE_CAPTURE 0
#define SIGNAL_HW_ENABLE_COMPARATOR 0
#define SIGNAL_HW_ENABLE_UART_DEBUG 1
#elif (SIGNAL_HW_PROFILE == SIGNAL_HW_PROFILE_FREQUENCY)
#define SIGNAL_HW_ENABLE_ADC_A 0
#define SIGNAL_HW_ENABLE_ADC_B 0
#define SIGNAL_HW_ENABLE_DAC 0
#define SIGNAL_HW_ENABLE_CAPTURE 1
#define SIGNAL_HW_ENABLE_COMPARATOR 1
#define SIGNAL_HW_ENABLE_UART_DEBUG 1
#elif (SIGNAL_HW_PROFILE == SIGNAL_HW_PROFILE_FULL_SIGNAL)
#define SIGNAL_HW_ENABLE_ADC_A 1
#define SIGNAL_HW_ENABLE_ADC_B 1
#define SIGNAL_HW_ENABLE_DAC 1
#define SIGNAL_HW_ENABLE_CAPTURE 1
#define SIGNAL_HW_ENABLE_COMPARATOR 1
#define SIGNAL_HW_ENABLE_UART_DEBUG 1
#else
#error "Unknown SIGNAL_HW_PROFILE"
#endif

#endif /* SIGNAL_HW_CONFIG_H */
