#ifndef SIGNAL_ANALYZER_FEATURES_H
#define SIGNAL_ANALYZER_FEATURES_H

#define SIGNAL_PROFILE_BASIC_MEASURE        (1U)
#define SIGNAL_PROFILE_FREQUENCY_PRECISION  (2U)
#define SIGNAL_PROFILE_SPECTRUM             (3U)
#define SIGNAL_PROFILE_THD                  (4U)
#define SIGNAL_PROFILE_PHASE                (5U)

#define PROFILE_BASIC_MEASURE        SIGNAL_PROFILE_BASIC_MEASURE
#define PROFILE_FREQUENCY_PRECISION  SIGNAL_PROFILE_FREQUENCY_PRECISION
#define PROFILE_SPECTRUM             SIGNAL_PROFILE_SPECTRUM
#define PROFILE_THD                  SIGNAL_PROFILE_THD
#define PROFILE_PHASE                SIGNAL_PROFILE_PHASE

#ifndef SIGNAL_PROCESSING_PROFILE
#define SIGNAL_PROCESSING_PROFILE SIGNAL_PROFILE_SPECTRUM
#endif

#define SIGNAL_PROFILE_IS_BASIC \
    (SIGNAL_PROCESSING_PROFILE == SIGNAL_PROFILE_BASIC_MEASURE)
#define SIGNAL_PROFILE_IS_FREQUENCY \
    (SIGNAL_PROCESSING_PROFILE == SIGNAL_PROFILE_FREQUENCY_PRECISION)
#define SIGNAL_PROFILE_IS_SPECTRUM \
    (SIGNAL_PROCESSING_PROFILE == SIGNAL_PROFILE_SPECTRUM)
#define SIGNAL_PROFILE_IS_THD \
    (SIGNAL_PROCESSING_PROFILE == SIGNAL_PROFILE_THD)
#define SIGNAL_PROFILE_IS_PHASE \
    (SIGNAL_PROCESSING_PROFILE == SIGNAL_PROFILE_PHASE)

#ifndef SIGNAL_FEATURE_DC
#define SIGNAL_FEATURE_DC            SIGNAL_PROFILE_IS_BASIC
#endif
#ifndef SIGNAL_FEATURE_MIN_MAX
#define SIGNAL_FEATURE_MIN_MAX       SIGNAL_PROFILE_IS_BASIC
#endif
#ifndef SIGNAL_FEATURE_VPP
#define SIGNAL_FEATURE_VPP           SIGNAL_PROFILE_IS_BASIC
#endif
#ifndef SIGNAL_FEATURE_RMS
#define SIGNAL_FEATURE_RMS           SIGNAL_PROFILE_IS_BASIC
#endif
#ifndef SIGNAL_FEATURE_AC_RMS
#define SIGNAL_FEATURE_AC_RMS        SIGNAL_PROFILE_IS_BASIC
#endif
#ifndef SIGNAL_FEATURE_FREQUENCY
#define SIGNAL_FEATURE_FREQUENCY     (SIGNAL_PROFILE_IS_BASIC || SIGNAL_PROFILE_IS_FREQUENCY)
#endif
#ifndef SIGNAL_FEATURE_SPECTRUM
#define SIGNAL_FEATURE_SPECTRUM      (SIGNAL_PROFILE_IS_SPECTRUM || SIGNAL_PROFILE_IS_THD)
#endif
#ifndef SIGNAL_FEATURE_FUNDAMENTAL
#define SIGNAL_FEATURE_FUNDAMENTAL   (SIGNAL_PROFILE_IS_SPECTRUM || SIGNAL_PROFILE_IS_THD)
#endif
#ifndef SIGNAL_FEATURE_HARMONICS
#define SIGNAL_FEATURE_HARMONICS     SIGNAL_PROFILE_IS_THD
#endif
#ifndef SIGNAL_FEATURE_THD
#define SIGNAL_FEATURE_THD           SIGNAL_PROFILE_IS_THD
#endif
#ifndef SIGNAL_FEATURE_SNR
#define SIGNAL_FEATURE_SNR           SIGNAL_PROFILE_IS_SPECTRUM
#endif
#ifndef SIGNAL_FEATURE_SFDR
#define SIGNAL_FEATURE_SFDR          SIGNAL_PROFILE_IS_SPECTRUM
#endif
#ifndef SIGNAL_FEATURE_PHASE
#define SIGNAL_FEATURE_PHASE         SIGNAL_PROFILE_IS_PHASE
#endif

#if (SIGNAL_PROCESSING_PROFILE < SIGNAL_PROFILE_BASIC_MEASURE) || \
    (SIGNAL_PROCESSING_PROFILE > SIGNAL_PROFILE_PHASE)
#error "Invalid SIGNAL_PROCESSING_PROFILE"
#endif

#endif
