#ifndef SIGNAL_CONTEST_FEATURES_H
#define SIGNAL_CONTEST_FEATURES_H

#define SIGNAL_CONTEST_PROFILE_BASIC     (1U)
#define SIGNAL_CONTEST_PROFILE_SPECTRUM  (2U)
#define SIGNAL_CONTEST_PROFILE_THD       (3U)
#define SIGNAL_CONTEST_PROFILE_PHASE     (4U)

#ifndef SIGNAL_CONTEST_PROFILE
#define SIGNAL_CONTEST_PROFILE SIGNAL_CONTEST_PROFILE_BASIC
#endif

#define SIGNAL_CONTEST_ENABLE_BASIC \
    (SIGNAL_CONTEST_PROFILE == SIGNAL_CONTEST_PROFILE_BASIC)
#define SIGNAL_CONTEST_ENABLE_SPECTRUM \
    (SIGNAL_CONTEST_PROFILE == SIGNAL_CONTEST_PROFILE_SPECTRUM)
#define SIGNAL_CONTEST_ENABLE_THD \
    (SIGNAL_CONTEST_PROFILE == SIGNAL_CONTEST_PROFILE_THD)
#define SIGNAL_CONTEST_ENABLE_PHASE \
    (SIGNAL_CONTEST_PROFILE == SIGNAL_CONTEST_PROFILE_PHASE)

#if (SIGNAL_CONTEST_PROFILE < SIGNAL_CONTEST_PROFILE_BASIC) || \
    (SIGNAL_CONTEST_PROFILE > SIGNAL_CONTEST_PROFILE_PHASE)
#error "Invalid contest processing profile"
#endif

#endif
